In [1]:
import numpy as np
import pandas as pd
from sklearn import feature_extraction, model_selection, linear_model, preprocessing

In [2]:
train_df = pd.read_csv('./nlp-getting-started/train.csv')
test_df = pd.read_csv('./nlp-getting-started/test.csv')

## Vectors

In [3]:
counter_vectorizer = feature_extraction.text.CountVectorizer()

In [4]:
sample_train_vectors = counter_vectorizer.fit_transform(train_df.text[:3])
print(sample_train_vectors[0].todense().shape)
print(sample_train_vectors[0].todense())
print(sample_train_vectors[1].todense().shape)
print(sample_train_vectors[1].todense())
print(sample_train_vectors[2].todense().shape)
print(sample_train_vectors[2].todense())
train_df.text[:3]

(1, 36)
[[1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1]]
(1, 36)
[[0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]]
(1, 36)
[[1 0 2 1 1 1 0 0 0 1 1 0 0 0 2 0 0 0 1 1 0 1 1 1 1 0 2 0 1 0 0 2 0 0 1 0]]


0    Our Deeds are the Reason of this #earthquake M...
1               Forest fire near La Ronge Sask. Canada
2    All residents asked to 'shelter in place' are ...
Name: text, dtype: object

13 words: Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all                                                                
7 words: Forest fire near La Ronge Sask. Canada                                                                                               
22 words (16 new): residents asked to 'shelter in place' being notified by officers. No other evacuation or orders expected

In [5]:
words = train_df.text[0] + ' ' + train_df.text[1] + ' '+ train_df.text[2]
words = words.replace('#','').replace('.',' ').replace("\'"," ")
words = words.lower().split()
words = sorted(list(set(words)))
print(words)

['all', 'allah', 'are', 'asked', 'being', 'by', 'canada', 'deeds', 'earthquake', 'evacuation', 'expected', 'fire', 'forest', 'forgive', 'in', 'la', 'may', 'near', 'no', 'notified', 'of', 'officers', 'or', 'orders', 'other', 'our', 'place', 'reason', 'residents', 'ronge', 'sask', 'shelter', 'the', 'this', 'to', 'us']


In [6]:
len(words)

36

In [7]:
train_vectors = counter_vectorizer.fit_transform(train_df.text)
test_vectors = counter_vectorizer.transform(test_df.text)